export const DEFAULT_AMQP_CONNECTION = 'default-AMQP_CONNECTION'
export const DEFAULT_AMQP_PUB_CHANNEL = 'default-AMQP_PUB_CHANNEL'
export const DEFAULT_AMQP_SUB_CHANNEL = 'default-AMQP_SUB_CHANNEL'
export const DEFAULT_AMQP_CONFIG = 'default-AMQP_CONFIG'
// TODO: Delete AMQP_MODULE_OPTIONS
export const AMQP_MODULE_OPTIONS = 'AMQP_MODULE_OPTIONS'
export const AMQP_CLIENT = 'AMQP_CLIENT'
export const AMQP_QUEUE_CONSUMER = '__amqp_module_queue_consumer'
export const AMQP_CONTROLLER = '__amqp_module_controller'
export const AMQP_CONNECTION_NAME = 'AMQP_CONNECTION_NAME'
