name: Publish package to NPM
on: 
  release:
    type: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm ci
    - name: Publish to NPM
      run: npm run publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
