name: My First Manual Workflow
on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm ci
    - name: Set up .npmrc with the publish token
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
    - name: Build, Release and Publish
      run: npm run release
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
